#PBS -N test_cuda
#PBS -q testegpu
#PBS -m abe
#PBS -e test_cuda_errors 
#PBS -o test_cuda_output

#unset CUDA_VISIBLE_DEVICES

#source ~/research/white-mold-applications/wm-model-yolo-v8/venv-wm-model-yolo-v8/bin/activate
####### module load cuda/11.5.0-intel-2022.0.1
#module load cuda/12.0.0-intel-2023.2.1


module load cuda/12.0.0
source /home/lovelace/proj/proj939/rubenscp/CENAPAD/miniconda3.sh
unset CUDA_VISIBLE_DEVICES

python ~/research/white-mold-applications/wm-model-yolo-v8/my-python-modules/test_cuda.py