#PBS -N yolo_train
#PBS -q duasgpus
#PBS -m abe
#PBS -e yolo_train_errors 
#PBS -o yolo_train_output

unset CUDA_VISIBLE_DEVICES

source ~/research/white-mold-applications/wm-model-yolo-v8/venv-wm-model-yolo-v8/bin/activate
####### module load cuda/11.5.0-intel-2022.0.1
module load cuda/12.0.0-intel-2023.2.1
python ~/research/white-mold-applications/wm-model-yolo-v8/my-python-modules/manage_yolo_train.py
