#PBS -N yolo_test
#PBS -q testegpu
#PBS -m abe
#PBS -e yolo_test_errors 
#PBS -o yolo_test_output

unset CUDA_VISIBLE_DEVICES

### module load cuda/11.5.0-intel-2022.0.1
### module load cuda/12.0.0-intel-2023.2.1

source ~/research/white-mold-applications/wm-model-yolo-v8/venv-wm-model-yolo-v8/bin/activate
module load cuda/11.5.0-intel-2019.0.5
python ~/research/white-mold-applications/wm-model-yolo-v8/my-python-modules/manage_yolo_test.py